#!/bin/sh /etc/rc.common
# Run the SOCKS health-check daemon under procd.
START=95
STOP=10
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/sbproxy-healthd
  procd_set_param respawn 3600 5 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
